import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import { store, persistor } from '@/context/store';
import Head from 'next/head';
import Footer from '@/components/Footer';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <Head>
          <title>AutoDoc</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="min-h-screen relative antialiased tracking-tight text-gray-500 bg-black font-inter">
          <div className="absolute inset-0 bg-no-repeat bg-top bg-illustration-01" />
          <div className="absolute inset-0 bg-no-repeat bg-center bg-illustration-02 min-h-screen" />
          <div className="container relative min-h-screen">
            <Component {...pageProps} />
            <Footer />
          </div>

        </div>
      </PersistGate >
    </Provider >
  )
}

